name: 'Deploy with kustomize'
description: 'This action compiles your kustomize manifests and deploys it with kubectl'
inputs:
  registry:
    description: 'Registry to the docker images'
    required: false
  images:
    description: 'The images to edit to a new image version. Note its currently hardcoded to change from :latest to a version you provide'
    required: false
  overlay:
    description: 'The path to the overlay to kustomize'
    required: true
  monitoring:
    description: 'Enables kubectl rollout checks on all Deployments, statefulsets and daemonsets within the compiled manifest'
    required: false
  kustomize:
    description: 'The version of kustomize to use'
    required: true
    default: '4.4.1'
  kubectl:
    description: 'The version of kustomize to use'
    required: true
    default: '1.20.9'
  namesuffix:
    description: 'Add suffix to all resources'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
